# Generated by Django 4.2.23 on 2025-07-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='is_mais_vendido',
            field=models.BooleanField(default=False, verbose_name='Exibir no carrossel da home'),
        ),
    ]
