"""
Django settings for jardim_da_diana project.

Generated by 'django-admin startproject' using Django 5.2.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Static files (favicon, CSS, JS, imagens)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-we(g3hxs$fn@lc9v$xzcz3+tn^1fn++6_yfq@zd@d1ywhnpifv'
DEBUG = True
ALLOWED_HOSTS = []

# ================================================================
#                       CONFIGURAÇÕES DE CORS
# ================================================================
# CORRIGIDO: Removida a linha 'CORS_ALLOW_ALL_ORIGINS' que é menos segura.
#            Mantida apenas a lista de origens permitidas.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5500",
]

# ID da sessão para o carrinho de compras
CART_SESSION_ID = 'carrinho'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'produtos',
    'usuarios',
    'cart',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jardim_da_diana.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'jardim_da_diana.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ================================================================
#                  IDIOMA E FUSO HORÁRIO
# ================================================================
# CORRIGIDO: Ajustado para Português do Brasil e fuso de São Paulo.
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# Configura o Django para 'enviar' e-mails para o console/terminal
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ================================================================
#       CONFIGURAÇÕES GLOBAIS DE AUTENTICAÇÃO
# ================================================================
# ATENÇÃO: As rotas abaixo são customizadas. Garanta que seu arquivo
#          `urls.py` tenha padrões de URL que correspondam a elas.

# 1. Para onde redirecionar APÓS O LOGIN BEM-SUCEDIDO.
LOGIN_REDIRECT_URL = '/'

# 2. Para onde redirecionar APÓS O LOGOUT.
LOGOUT_REDIRECT_URL = '/auth/login/'

# 3. Qual é a URL da sua página de login.
#    Usado pelo @login_required para saber para onde enviar usuários não logados.
LOGIN_URL = '/auth/login/'